[package]
name = "pod"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2"
libc = "0.2"
errno = "0.3"
cookie-factory = "0.3.2"
nom = "7"

spa_sys = { package = "libspa-consts", version = "0", path = "../libspa-consts" }
pod-derive = { path = "../pod-derive/" }
